version: '3.7'
services:
  app:
    build: .
    command: sh -c "npm start"
    ports:
      - "4200:4200"
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app
      - node_modules:/home/node/app/node_modules
    depends_on:
      - surrealdb

  surrealdb:
    image: surrealdb/surrealdb:latest
    container_name: surrealdb
    restart: always
    command: start --user admin --pass admin file:/data/database.db
    ports:
      - "8000:8000"
    volumes:
      - ./data:/data

volumes:
  node_modules:

